CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra -Werror

all: ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9

ex8.o: euclid.h

ex8: euclid.o

ex9.o: euclid.h

ex9: euclid.o

clean:
	rm -f ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9 *.o
